### PR TITLE
Add Google Play & F-Droid Badges

### PR DESCRIPTION
**Pull request by mayailkour**
I added badges for Google Play & F-Droid.

### CODE REVIEW

**Comment by MicMun** [comment]
This app isn't in F-Droid and will never be. The badge for Google Play is a great idea.
If you remove the F-Droid badge and commit it, I will merge your request.

**Comment by mayailkour** [comment]
I removed the F-Droid badge.

May you tell me why you dislike F-Droid? To be honest, I am thinking extremely positive about them. 🤔

**Comment by MicMun** [comment]
I don't dislike F-Droid, my app DeuFeiTage is in F-Droid.
But this app is only for a little group of people from my church and they aren't technicals.
So there is no reason to put the app in F-Droid.

**Comment by mayailkour** [comment]
Ah, I see. 👍

**Pull request merged**
